import React from "react";
import { Link } from "react-router-dom";
import QuickItem from "../quickItem/quickItem";
import styles from "./QuickList.module.css";

const QuickList = () => {
  const recipesList = [
    {
      id: 1,
      name: "CÁCH LÀM GÀ ĂN MÀY CAO SANG QUYỀN QUÝ",
      thumb: "./img/recipes/ga-an-may.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "spring",
      region: "north",
      category: "main",
      method: "grill",
      ingredient: "Thịt gà",
    },

    {
      id: 2,
      name: "HÀU NƯỚNG PHOMAI NGON NHẤT THẾ GIỚI",
      thumb: "./img/recipes/hau-nuong.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "summer",
      region: "north",
      category: "sub",
      method: "grill",
      ingredient: "Hàu, Phô mai",
    },
    {
      id: 3,
      name: "XÔI GÀ",
      thumb: "./img/recipes/xoi-ga.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "fall",
      region: "north",
      category: "sub",
      method: "boil",
      ingredient: "Xôi nếp, thịt gà",
    },

    {
      id: 4,
      name: "CÁCH LỌC XƯƠNG GÀ LUỘC CỰC DỄ",
      thumb: "./img/recipes/ga-luoc.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "winter",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Thịt gà",
    },

    {
      id: 5,
      name: "CÁCH MUỐI CÁ HỒI RUBY SIÊU TO KHỔNG LỒ",
      thumb: "./img/recipes/ca-hoi.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "spring",
      region: "north",
      category: "sub",
      method: "boil",
      ingredient: "Cá hồi",
    },

    {
      id: 6,
      name: "CÁ TRẮM KHO MĂNG CAY BẰNG NỒI ÁP SUẤT",
      thumb: "./img/recipes/ca-tram.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "summer",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Cá trắm, măng",
    },

    {
      id: 7,
      name: "CÁ VƯỢC OM XỐT YOSENABE KIỂU NHẬT",
      thumb: "./img/recipes/ca-vuoc.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "fall",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Cá vược",
    },

    {
      id: 8,
      name: "THỊT KHÂU NHỤC KIỂU QUẢNG ĐÔNG",
      thumb: "./img/recipes/khau-nhuc.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "winter",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Thịt lợn",
    },
    {
      id: 9,
      name: "CÁCH LÀM GÀ NƯỚNG CAY XÈ PIRI PIRI",
      thumb: "./img/recipes/ga-nuong.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "spring",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Thịt gà",
    },
    {
      id: 10,
      name: "MẸO CHIÊN CÁ GIÒN TAN Bằng NCKD",
      thumb: "./img/recipes/ca-chien.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "summer",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Cá",
    },
    {
      id: 11,
      name: "TỰ LÀM THỊT QUAY GIÒN BÌ",
      thumb: "./img/recipes/thit-quay.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 45,
      season: "fall",
      region: "north",
      category: "main",
      method: "boil",
      ingredient: "Thịt lợn",
    },
    {
      id: 12,
      name: "BÁNH MỲ TRỨNG ỐP LA",
      thumb: "./img/recipes/thit-quay.png",
      auth: "Hà Vy",
      day: "13",
      month: "March",
      date: "March 13, 2021",
      duration: 30,
      season: "fall",
      region: "north",
      category: "sub",
      method: "boil",
      ingredient: "Bánh mỳ, trứng",
    },
    {
      id: 13,
      name: "THỊT BÒ SỐT TIÊU ĐEN",
      thumb: "./img/recipes/bo-sot-tieu.png",
      auth: "Vinh Trần",
      day: "15",
      month: "August",
      date: "August 15, 2022",
      duration: 20,
      season: "winter",
      region: "north",
      category: "main",
      method: "fry",
      ingredient: "Thịt bò",
    },
    {
      id: 14,
      name: "BÁNH MỲ NƯỚNG BƠ TỎI",
      thumb: "./img/recipes/banh-my-nuong-bo-toi.png",
      auth: "Hà Đặng",
      day: "18",
      month: "Jul",
      date: "Jul 18, 2021",
      duration: 15,
      season: "winter",
      region: "north",
      category: "cake",
      method: "grill",
      ingredient: "Bánh mỳ",
    },
    {
      id: 15,
      name: "MỲ XÀO RAU CỦ",
      thumb: "./img/recipes/my-xao-rau-cu.png",
      auth: "Dương Thái",
      day: "10",
      month: "July",
      date: "July 10 2021",
      duration: 25,
      season: "fall",
      region: "south-side",
      category: "sub",
      method: "fried",
      ingredient: "Mỳ, rau củ, trứng",
    },
    {
      id: 16,
      name: "BÁNH MỲ SANWICH",
      thumb: "./img/recipes/sanwich.png",
      auth: "Khánh Trần",
      day: "18",
      month: "September",
      date: "September 18, 2020",
      duration: 15,
      season: "summer",
      region: "north-side",
      category: "cake",
      method: "grill",
      ingredient: "Bánh mỳ, trứng",
    },
    {
      id: 17,
      name: "CƠM CHIÊN THẬP CẨM",
      thumb: "./img/recipes/com-chien.png",
      auth: "Tuấn Đặng",
      day: "16",
      month: "December",
      date: "December 16, 2021",
      duration: 18,
      season: "winter",
      region: "south-side",
      category: "main",
      method: "fried",
      ingredient: "Cơm, trứng, tôm",
    },
    {
      id: 18,
      name: "BÁNH MỲ TRỨNG ỐP LA",
      thumb: "./img/recipes/banh-my-trung.png",
      auth: "Hà Trần",
      day: "19",
      month: "Febuary",
      date: "Febuary 19, 2020",
      duration: 15,
      season: "summer",
      region: "south-side",
      category: "summer",
      method: "grill",
      ingredient: "Bánh mỳ, trứng",
    },
    {
      id: 19,
      name: "BÁNH MỲ KAYA TOAST",
      thumb: "./img/recipes/banh-brazil.png",
      auth: "Ngọc Hân",
      day: "22",
      month: "March",
      date: "March 22, 2022",
      duration: 30,
      season: "winter",
      region: "south-side",
      category: "cake",
      method: "grill",
      ingredient: "Bánh mỳ, thịt nguội",
    },
    {
      id: 20,
      name: "NGŨ CỐC CÁC LOẠI",
      thumb: "./img/recipes/ngu-coc.png",
      auth: "Tú Trần",
      day: "01",
      month: "March",
      date: "March 01, 2019",
      duration: 10,
      season: "fall",
      region: "south-side",
      category: "sub",
      method: "salad",
      ingredient: "Ngũ cốc",
    },
    {
      id: 21,
      name: "GỎI CỦ HŨ DỪA",
      thumb: "./img/recipes/cu-hu-dua.png",
      auth: "Khánh Đặng",
      day: "21",
      month: "July",
      date: "July 21, 2020",
      duration: 45,
      season: "summer",
      region: "south-side",
      category: "appetizer",
      method: "salad",
      ingredient: "Tôm, củ hũ dừa",
    },
    {
      id: 22,
      name: "GỎI NGÓ SEN TÔM THỊT",
      thumb: "./img/recipes/goi-ngo-sen-tom-thit.png",
      auth: "Huệ Đặng",
      day: "25",
      month: "July",
      date: "July 25, 2020",
      duration: 45,
      season: "summer",
      region: "south-side",
      category: "appetizer",
      method: "salad",
      ingredient: "Tôm, thịt, ngó sen",
    },
    {
      id: 23,
      name: "GỎI HOA CHUỐI",
      thumb: "./img/recipes/goi-hoa-chuoi.png",
      auth: "Huệ Hồng",
      day: "25",
      month: "August",
      date: "August 25, 2020",
      duration: 50,
      season: "summer",
      region: "north-side",
      category: "appetizer",
      method: "salad",
      ingredient: "Thịt lợn, hoa chuối",
    },
    {
      id: 24,
      name: "GỎI BÒ MÈ BÓP THẤU",
      thumb: "./img/recipes/bo-me-bop-thau.png",
      auth: "Diệp Anh",
      day: "18",
      month: "August",
      date: "August 18, 2022",
      duration: 50,
      season: "summer",
      region: "south-side",
      category: "appetizer",
      method: "salad",
      ingredient: "Thịt bò",
    },
    {
      id: 25,
      name: "BÁNH TRÁNG CUỘN",
      thumb: "./img/recipes/thit-nguoi.png",
      auth: "Lan Anh",
      day: "05",
      month: "Jul",
      date: "Jul 05, 2022",
      duration: 50,
      season: "summer",
      region: "central",
      category: "appetizer",
      method: "salad",
      ingredient: "Bánh tráng, thịt lợn, nem lụi",
    },
    {
      id: 26,
      name: "CÀNG CUA BÁCH HOA",
      thumb: "./img/recipes/cang-cua-bach-hoa.png",
      auth: "Giang Trần",
      day: "17",
      month: "Jul",
      date: "Jul 17, 2022",
      duration: 50,
      season: "summer",
      region: "central",
      category: "appetizer",
      method: "salad",
      ingredient: "Càng cua",
    },
    {
      id: 27,
      name: "TRÀ SỮA BÍ ĐAO",
      thumb: "./img/recipes/tra-bi-dao.png",
      auth: "Huệ Anh",
      day: "17",
      month: "October",
      date: "October 17, 2022",
      duration: 60,
      season: "summer",
      region: "south-side",
      category: "beverage",
      method: "boil",
      ingredient: "Bí đao, sữa, trà",
    },
    {
      id: 28,
      name: "HẠT ĐÁC RIM DỨA & CHANH LEO",
      thumb: "./img/recipes/hat-dac.png",
      auth: "Loan Phạm",
      day: "21",
      month: "October",
      date: "October 21, 2022",
      duration: 60,
      season: "summer",
      region: "north-side",
      category: "beverage",
      method: "boil",
      ingredient: "Hạt đác",
    },
    {
      id: 29,
      name: "CÁCH LÀM KOMBUCHA ĐÀO “LƯỜI”",
      thumb: "./img/recipes/dao-luoi.png",
      auth: "hà Phạm",
      day: "21",
      month: "November",
      date: "November 21, 2022",
      duration: 60,
      season: "summer",
      region: "north-side",
      category: "beverage",
      method: "boil",
      ingredient: "Đào",
    },
    {
      id: 30,
      name: "CÁCH LÀM LASSI “SỮA CHUA LẮC KIỂU ẤN”",
      thumb: "./img/recipes/lac-an.png",
      auth: "Hoa Lan",
      day: "21",
      month: "Febuary",
      date: "Febuary 17, 2021",
      duration: 60,
      season: "summer",
      region: "north-side",
      category: "beverage",
      method: "boil",
      ingredient: "Sữa chua",
    },

    {
      id: 31,
      name: "CÀ PHÊ ĐÁ XAY CỐT DỪA THẠCH CARAMEL ",
      thumb: "./img/recipes/ca-phe.png",
      auth: "Tuấn Khanh",
      day: "19",
      month: "Febuary",
      date: "Febuary 19, 2022",
      duration: 15,
      season: "summer",
      region: "south-side",
      category: "beverage",
      method: "boil",
      ingredient: "Cà phê",
    },

    {
      id: 32,
      name: "CHÈ ĐẬU ",
      thumb: "./img/recipes/che-dau.png",
      auth: "Trang Thu",
      day: "16",
      month: "October",
      date: "October 16, 2021",
      duration: 50,
      season: "summer",
      region: "central",
      category: "dessert",
      method: "tea",
      ingredient: "Đậu đen",
    },
    {
      id: 33,
      name: "CHÈ VẢI HẠT SEN ",
      thumb: "./img/recipes/che-vai-hat-sen.png",
      auth: "Nghĩa Lưu",
      day: "20",
      month: "Jul",
      date: "Jul 20, 2021",
      duration: 50,
      season: "summer",
      region: "south-side",
      category: "dessert",
      method: "tea",
      ingredient: "Hạt sen",
    },
    {
      id: 33,
      name: " BÁNH CHUỐI NƯỚNG",
      thumb: "./img/recipes/banh-chuoi-nuong.png",
      auth: "Ninh Lan",
      day: "20",
      month: "Jul",
      date: "Jul 20, 2021",
      duration: 40,
      season: "winter",
      region: "central",
      category: "dessert",
      method: "grill",
      ingredient: "Chuối",
    },
    {
      id: 34,
      name: "BÁNH DA LỢN",
      thumb: "./img/recipes/banh-da-lon.png",
      auth: "Ninh Lan",
      day: "19",
      month: "May",
      date: "May 19, 2022",
      duration: 60,
      season: "summer",
      region: "central",
      category: "dessert",
      method: "cake",
      ingredient: "Bột, sữa",
    },
    {
      id: 35,
      name: "SƯƠNG SÁO NƯỚC CỐT DỪA",
      thumb: "./img/recipes/suong-sao-cot-dua.png",
      auth: "Phan Anh",
      day: "30",
      month: "August",
      date: "August 30, 2020",
      duration: 120,
      season: "summer",
      region: "central",
      category: "dessert",
      method: "beverage",
      ingredient: "Sương sáo, nước dừa",
    },
    {
      id: 36,
      name: "BÁNH CHUỐI HẤP NƯỚC CỐT DỪA",
      thumb: "./img/recipes/banh-chuoi-hap.png",
      auth: "Phan Anh",
      day: "27",
      month: "January",
      date: "January 27, 2020",
      duration: 45,
      season: "summer",
      region: "central",
      category: "dessert",
      method: "boil",
      ingredient: "Chuối, nước cốt dừa",
    },
  ];

  const quickList = recipesList.filter(
    (quickRecipes) => quickRecipes.duration <= 30
  );
  const listQuick = quickList.slice(0, 6).map((quickItem, index) => {
    return <QuickItem key={index} quickItem={quickItem} />;
  });

  return (
    <div className="content">
      <div className="row ">{listQuick}</div>
      <Link to="/recipes">
        <button
          className={`${styles["btn-see-all"]} ${styles["btn-quick-meal"]} d-sm-none`}
        >
          Xem tất cả
        </button>
      </Link>
    </div>
  );
};

export default QuickList;
